const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../src/lib/locales');
const outputFile = path.join(localesDir, 'index.ts');

function generateLocalesIndex() {
  if (!fs.existsSync(localesDir)) {
    console.error(`Locales directory not found: ${localesDir}`);
    process.exit(1);
  }

  const langDirs = fs.readdirSync(localesDir).filter(f => {
    const fullPath = path.join(localesDir, f);
    return fs.statSync(fullPath).isDirectory() && f !== 'all';
  });

  const imports = [];
  const resourceStructure = {};

  langDirs.forEach(lang => {
    const langPath = path.join(localesDir, lang);
    const jsonFiles = fs.readdirSync(langPath).filter(f => f.endsWith('.json'));

    resourceStructure[lang] = {};

    jsonFiles.forEach(file => {
      const ns = file.replace('.json', '');
      // Create a safe import identifier, e.g., lang_ns
      const importId = `${lang.replace(/[^a-zA-Z0-9]/g, '_')}_${ns.replace(/[^a-zA-Z0-9]/g, '_')}`;
      const relativePath = `./${lang}/${file}`;

      imports.push(`import ${importId} from '${relativePath}';`);
      resourceStructure[lang][ns] = importId;
    });
  });

  // Build the resources output structure string
  let resourcesStr = 'export const resources: any = {\n';
  Object.entries(resourceStructure).forEach(([lang, nsMap]) => {
    resourcesStr += `  '${lang}': {\n`;
    Object.entries(nsMap).forEach(([ns, importId]) => {
      resourcesStr += `    '${ns}': ${importId},\n`;
    });
    resourcesStr += '  },\n';
  });
  resourcesStr += '};\n';

  const outputContent = `// This file is auto-generated by scripts/generate-locales.cjs. Do not edit manually.
${imports.join('\n')}

${resourcesStr}
`;

  fs.writeFileSync(outputFile, outputContent, 'utf-8');
  console.log(`Generated locales index successfully at ${outputFile}`);
}

generateLocalesIndex();
